"""
Writes generated content directly into the live site files.

  patch_blog_post(post) - appends a new post to App.tsx.

Sitemap and RSS output are generated by `npm run build` via prerender.mjs.
Do not patch public/sitemap.xml directly.
"""

import logging
import re
from pathlib import Path

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
APP_TSX = REPO_ROOT / "src" / "App.tsx"


def _ts_string(s: str) -> str:
    """Escape a Python string for a TypeScript single-quoted string."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def _format_post_ts(post: dict) -> str:
    """Render a post dict as a TypeScript object literal with 2-space indent."""
    slug = _ts_string(post["slug"])
    title = _ts_string(post["title"])
    desc = _ts_string(post["description"])
    updated = _ts_string(post["updated"])
    audience = _ts_string(post["audience"])

    takeaways = "\n".join(f"      '{_ts_string(t)}'," for t in post["takeaways"])
    section_parts = []
    for section in post["sections"]:
        heading = _ts_string(section["heading"])
        body = _ts_string(section["body"])
        section_parts.append(
            "      {\n"
            f"        heading: '{heading}',\n"
            f"        body: '{body}',\n"
            "      },"
        )
    sections = "\n".join(section_parts)

    return (
        "  {\n"
        f"    slug: '{slug}',\n"
        f"    title: '{title}',\n"
        "    description:\n"
        f"      '{desc}',\n"
        f"    updated: '{updated}',\n"
        f"    audience: '{audience}',\n"
        "    takeaways: [\n"
        f"{takeaways}\n"
        "    ],\n"
        "    sections: [\n"
        f"{sections}\n"
        "    ],\n"
        "  },"
    )


def _find_posts_array_end(content: str) -> int:
    """
    Return the index of the closing ] of the blogPosts array.
    Uses bracket-depth counting from the array's opening [.
    """
    marker = "export const blogPosts = ["
    start = content.find(marker)
    if start == -1:
        raise ValueError("blogPosts array not found in App.tsx")

    pos = start + len(marker) - 1
    depth = 0
    for i in range(pos, len(content)):
        ch = content[i]
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("Could not find closing ] of blogPosts array")


def get_existing_slugs() -> list[str]:
    """Read App.tsx and extract all existing blog post slugs."""
    content = APP_TSX.read_text(encoding="utf-8")
    return re.findall(r"slug:\s*'([^']+)'", content)


def patch_app_tsx(post: dict) -> None:
    """Insert a new blog post into App.tsx blogPosts array."""
    content = APP_TSX.read_text(encoding="utf-8")

    if f"slug: '{post['slug']}'" in content:
        log.warning("Slug '%s' already exists in App.tsx - skipping", post["slug"])
        return

    end_idx = _find_posts_array_end(content)
    ts_block = "\n" + _format_post_ts(post) + "\n"
    new_content = content[:end_idx] + ts_block + content[end_idx:]

    APP_TSX.write_text(new_content, encoding="utf-8")
    log.info("App.tsx patched - added '%s'", post["slug"])


def patch_sitemap(post: dict) -> None:
    """No-op: sitemap.xml and feed.xml are generated from blogPosts during build."""
    log.info(
        "Sitemap/feed generation deferred to npm run build for post: %s",
        post["slug"],
    )


def patch_blog_post(post: dict) -> None:
    """Write a new blog post into App.tsx."""
    patch_app_tsx(post)
    patch_sitemap(post)
    log.info("Site patched successfully for post: %s", post["slug"])
