"""
Writes the weekly call sheet CSV and creates a GitHub Issue summary.
"""

import csv
import json
import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path

import requests

from config import LEADS_DIR, SENDER_PHONE, SENDER_SITE

log = logging.getLogger(__name__)

# ── Cerebras talking-point prompt ────────────────────────────────────────────
_TP_PROMPT = """\
Write a 15-word cold-call opening line for a web designer reaching out to a {category} company
called "{name}" in {town}, NJ that has no website. Format: one plain sentence. No greeting, no
"Hi" — just the hook. Example: "Noticed {name} doesn't come up when people search for {category}
in {town} — wanted to see if that's something you'd want to fix."
Return ONLY the sentence, nothing else.
"""


def _iso_week() -> str:
    now = datetime.now(timezone.utc)
    return f"{now.year}-W{now.strftime('%V')}"


def _template_point(lead: dict) -> str:
    town = lead.get("location", "NJ")
    return (
        f"Noticed {lead['name']} doesn't show up when people search for "
        f"{lead['category']} in {town} — worth fixing?"
    )


def _talking_point(lead: dict, cerebras_client) -> str:
    from config import CEREBRAS_MODEL
    town = lead.get("location", "").replace(", NJ", "")
    try:
        resp = cerebras_client.chat.completions.create(
            model=CEREBRAS_MODEL,
            messages=[{"role": "user", "content": _TP_PROMPT.format(
                category=lead["category"],
                name=lead["name"],
                town=town,
            )}],
            temperature=0.4,
            max_completion_tokens=80,
        )
        return resp.choices[0].message.content.strip().strip('"')
    except Exception as exc:
        log.warning("Talking point failed for %s: %s", lead["name"], exc)
        return _template_point(lead)


def write_call_sheet(call_leads: list[dict], cerebras_client) -> str:
    """Write CSV call sheet. Returns the file path.

    Only the first CALL_SHEET_AI_LIMIT leads get an AI-generated talking point
    (those are the ones you'll dial this week); the rest get an instant
    templated line so a run with hundreds of leads stays fast.
    """
    from config import CALL_SHEET_AI_LIMIT

    Path(LEADS_DIR).mkdir(exist_ok=True)
    week = _iso_week()
    path = os.path.join(LEADS_DIR, f"{week}-call-sheet.csv")

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "name", "category", "phone", "address", "location",
            "yelp_url", "talking_point",
        ])
        writer.writeheader()
        for i, lead in enumerate(call_leads):
            row = {k: lead.get(k, "") for k in ["name", "category", "phone", "address", "location", "yelp_url"]}
            if i < CALL_SHEET_AI_LIMIT:
                row["talking_point"] = _talking_point(lead, cerebras_client)
            else:
                row["talking_point"] = _template_point(lead)
            writer.writerow(row)

    log.info("Call sheet written: %s (%d leads, %d AI talking points)",
             path, len(call_leads), min(len(call_leads), CALL_SHEET_AI_LIMIT))
    return path


def create_github_issue(
    emailed: list[dict],
    call_leads: list[dict],
    csv_path: str,
    gh_token: str,
    gh_repo: str,
) -> None:
    """Create a GitHub Issue summarising the weekly run."""
    week = _iso_week()
    total = len(emailed) + len(call_leads)

    # Sample email leads (up to 5) for preview
    sample_rows = ""
    for lead in emailed[:5]:
        sample_rows += f"- **{lead['name']}** ({lead['category']}, {lead['location']}) → {lead.get('email','?')}\n"

    # Sample call leads (up to 5)
    call_rows = ""
    for lead in call_leads[:5]:
        call_rows += f"- **{lead['name']}** ({lead['category']}, {lead['location']}) — {lead.get('phone','no phone')}\n"

    csv_rel = os.path.relpath(csv_path, os.path.join(os.path.dirname(__file__), "..", ".."))
    csv_rel = csv_rel.replace("\\", "/")

    body = f"""## Autonomous Lead Run — {week}

| Metric | Count |
|--------|-------|
| Total no-website businesses found | {total} |
| Cold emails sent | {len(emailed)} |
| Call sheet leads | {len(call_leads)} |

### Emails sent (first {min(5, len(emailed))})
{sample_rows or "_None this run_"}

### Call sheet sample (first {min(5, len(call_leads))})
{call_rows or "_None this run_"}

### Call sheet CSV
`{csv_rel}` — committed to this repo. Open it, sort by category, and start dialling.

---
*Generated by `.github/workflows/lead-finder.yml` — runs every Monday 8am ET*
"""

    url = f"https://api.github.com/repos/{gh_repo}/issues"
    headers = {
        "Authorization": f"token {gh_token}",
        "Accept": "application/vnd.github+json",
    }
    payload = {
        "title": f"[Leads] {week} — {len(emailed)} emailed, {len(call_leads)} on call sheet",
        "body": body,
        "labels": ["leads"],
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=10)
    if resp.status_code == 201:
        log.info("GitHub Issue created: %s", resp.json().get("html_url"))
    else:
        log.warning("Issue creation failed %d: %s", resp.status_code, resp.text[:200])
